sudo: required
services:
    - docker

before_install:
    - docker build -t oyelowo/docker-with-react -f Dockerfile.dev  .

script:
    - docker run -e CI=true oyelowo/docker-with-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-with-react"
    env: "DockerWithReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-150627575501"
    bucket_path: "docker-with-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
    